# Site settings
title: A Few Scribbles
email: stephenroth.sr@gmail.com
description: "Notes about code and other interests."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: flamdoodle1000
github_username:  Flamdoodle

# Build settings
markdown: kramdown
permalink: pretty
